# Generated by Django 4.2.19 on 2025-03-06 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator('Enter a valid email address')])),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
