# Generated by Django 4.2.19 on 2025-02-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
