# Generated by Django 4.2.19 on 2025-02-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_app', '0002_alter_user_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='email',
            field=models.EmailField(default='user@domain.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_account',
            name='password',
            field=models.CharField(default='password1234', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_account',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
