# Generated by Django 4.2.19 on 2025-03-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='user_email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user_account',
            name='user_password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
    ]
