# Generated by Django 4.2.19 on 2025-03-04 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_user_account_user_email_user_account_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='user_password',
        ),
    ]
